### ISSUE TITLE
packedRecrypt question

### ISSUE THREAD

**Issue by boev** [homenc/HElib#289]
I am using HElib actively and it works great. I am doing calculations in binary representation, meaning I encrypt bits as vector of Ctxts (NTL::Vec<Ctxt> for example). All the arithmeticOperations seem to work when the initial levels are enough.
I purposely set the L value lower than needed and expect the packedRecrypt function to refresh the ciphertexts, but somehow it fails. Has anyone had similar issue? Am I using it wrong, or should I tweak parameters somehow? 

About context: My context is bootstrappable and I am reading it from file, since its a client-server test application. packedRecrypt seems to work nicely and does not complain about missing parameters.

Here is some output with Lvls (I added prints to HElib's code):
```
Minimal capacity of a and b is: 297
Minimal capacity of plan is: 158
Minimal capacity of plan is: 158
Minimal capacity of plan is: 63
Minimal capacity of plan is: 63
Minimal capacity of plan is: 50
Minimal capacity of plan is: 50
Minimal capacity of plan is: 23
PACKED RECRYPT binaryArith.cpp....
At recryption.cpp...recrypting...
AFTER RECRYPT CAPACITY is: -70
We need(ed): 30
not enough levels for addition DAG
```

I thought that the 23 levels left are not enough for a recrypt so I added 70 to the BPL estimates for calling recrypt, but it always seems that recrypt is making things worse:

```
Minimal capacity of a and b is: 166
CALLING PACKED RECRYPT!!!!!
PACKED RECRYPT binaryArith.cpp....
At recryption.cpp...recrypting...
AFTER RECRYPT capacity is: 113
We need(ed): 150
not enough levels for comparison
```

Question on the side: is it normal for binary addition to be so greedy on the levels at start? it drops by factor of 2 or even more with every addition. Thanks for any help or suggestions.

**Comment by fionser** [comment]
The boolean circuit for adding two t-bit integers might use `t` AND gates with multiplicative depth of `t`. So it does requires a lots of levels.

**Comment by shaih** [comment]
The current HElib implementation does not do recryption in the middle of adding two numbers, it just assumes that there are enough levels for that. As such, you cannot use it for bignum additions. It should, however, be enough for adding 64-bit numbers and even more, since it can do addition of two t-bit numbers in something like log t levels. (I think that the exact number is log t +1, but I'm not quite sure.)

With each level probably taking something like 30 bits of capacity (depending on parameters), you should be able to add two 64-bit numbers if you had capacity of 200 bits or so. (Try calling buildModChain with L=200.)

Of course, if this comes at the middle of the computation, then you really need the capacity *at the end of recryption* to be sufficient for addition. So you need total capacity of 200 *plus whatever you need for recryption* (so maybe a total of L=1000??)

**Comment by boev** [comment]
Hi,
yes, this is all true and I am able to add two number, many times in fact. Actually for the whole computation to work I would need at least L = 330 and this is not much. For complex computations I can use a higher L and it all works. In the outpu you can even see I am adding a and b a couple of times successfully. My question is about the effect of packedRecrypt and what I am observing. The packedRecrypt should be a way to bring back the levels up but in fact it always brings them down, by a lot. In the example I have, packedRecrypt is called when lowest level of a and b is 23 and we end up with -70 after just using packedRecrypt. 
Here I thought to myself that packedRecrypt itself would need some levels to recrypt. So i called packedRecrypt when lowest level in a and b is 166 (2nd output) and it worked, but brought lowest level to 113. This is not an improvement, on the contrary - packedRecrypt always "eats" some levels, instead of bootstrapping and giving some.

So my question is if anyone is observing the same behavior. I will look further into what packed Recrypt actually does.
