### ISSUE TITLE
How to build example_program?

### ISSUE THREAD

**Issue by jamesdang** [homenc/HElib#305]
I have built and installed the HElib with option 1 - package build (recommended for most users) in the INSTALL.MD. I then tried to build the example_program. I ran "cmake ." successfully, but when I ran "make", I got a lot of errors. Here is my screenshot:

jamesdang@TGU:~/HElib-master/example_program$ cmake .
-- The CXX compiler identification is GNU 8.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jamesdang/HElib-master/example_program
jamesdang@TGU:~/HElib-master/example_program$ make
Scanning dependencies of target helib_example
[ 50%] Linking CXX executable helib_example
/usr/bin/ld: /usr/local/lib/libntl.a(lip.o): in function `redc(_ntl_gbigint_body*, _ntl_gbigint_body*, long, unsigned long, _ntl_gbigint_body*)':
/home/jamesdang/ntl-11.3.2/src/lip.cpp:5472: undefined reference to `__gmpn_addmul_1'
/usr/bin/ld: /home/jamesdang/ntl-11.3.2/src/lip.cpp:5484: undefined reference to `__gmpn_sub_n'
/usr/bin/ld: /usr/local/lib/libntl.a(lip.o): in function `_ntl_rem_struct_basic::eval(long*, _ntl_gbigint_body*, _ntl_tmp_vec*)':
/home/jamesdang/ntl-11.3.2/src/lip.cpp:7937: undefined reference to `__gmpn_mod_1'
.......................

Any help would be appreciated.

James

**Comment by boev** [comment]
Hello James,
Are you on Linux? Please make sure you have GMP and NTL installed. If you are not sure, I can help you.

**Comment by jamesdang** [comment]
Thank you Boev. I am on Ubuntu and I am a beginner. I have built and installed Helib without issues, but when I tried to build the example_program in this project, I got the above errors. Did you ever build the example_program? What commands should I run?

**Comment by boev** [comment]
Hi James,

Thanks for the info. Let's solve the problem.

What is the problem? -> The problem is that gmp and ntl are not linked when building helib_example.cpp. This could probably be solved by chaning the example_program/CMakeLists.txt file to find and link those accordingly. I find using Cmake for a single .cpp file to be a bit extreme, so here I am proposing the following workaround, assuming gmp and ntl are installed in default location /usr/local/lib:

1. Build and install HElib as described in INSTALL.MD, Option 2: library build (advanced). Summarized do the following:
```
cd HElib
mkdir build
cd build
cmake ..
sudo make install
```
That's it. Sudo is needed, as default install location would be /usr/local/lib. This will install the static library libhelib.a there.

2. Build the example program using plain g++
Using g++ directly is far easier when compiling just a single cpp file:
```
cd HElib/example_program
g++ -c helib_example.cpp -o helib_example.o
g++ -std=c++17 -O2 -Wall -pthread helib_example.o -o example -lhelib -lntl -lgmp
./example 
```
Done, `./example` runs the example program.

**Comment by jamesdang** [comment]
Hi boev, 
Both solution worked. Thank you very much!
