### ISSUE TITLE
How to select nBits according to level L in function buildModChain

### ISSUE THREAD

**Issue by WeiBenqiang** [homenc/HElib#368]
void buildModChain(Context& context, **long nBits**, long nDgts, bool willBeBootstrappable, long skHwt, long resolution,
long bitsInSpecialPrimes)
parameter **L** has become  **nBits**.For example,the level is L=10,what should the **nBits** is?Is there  any connection?

**Comment by esteffin** [comment]
The parameter `L` used to be the number of levels in the modulus chain when we had fixed-size moduli in the ciphertext modulus Q.  The maximum number of modulus switching operation was less or equal to `L`.

Since the introduction of the current finer grain noise management in 2018 HElib abandoned the concept of levels and moved onto the total number of bits of the modulus chain. In the current release of HElib that total number is `nBits`.

If you are still thinking in levels, start by considering 30-40 bits per level, so in your case `nBits` can be ~300-400 and see how you can accommodate the depth of your computation.

**Comment by WeiBenqiang** [comment]
THX!
