### ISSUE TITLE
How to run  examples?

### ISSUE THREAD

**Issue by DGQAQ** [homenc/HElib#432]
I am new, I just installed HElib and want to run examples by 

cd BGV_binary_arithmetic
cmake -Dhelib_DIR=/usr/local/share/cmake/helib

but there is an error .
wang@wang-virtual-machine:~/HElib/examples/BGV_binary_arithmetic$ cmake -Dhelib_DIR=/usr/local/share/cmake/helib
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wang/HElib/examples/BGV_binary_arithmetic

can you tell me how to run examples ? thanks.

**Comment by DGQAQ** [comment]
wang@wang-virtual-machine:~/HElib/examples/BGV_binary_arithmetic$ cmake -Dhelib_DIR=/usr/local/share/cmake
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    helib_DIR


-- Build files have been written to: /home/wang/HElib/examples/BGV_binary_arithmetic

**Comment by faberga** [comment]
@DGQAQ , Please follow the install instructions in the [README.md](https://github.com/homenc/HElib/blob/master/examples/README.md the README.md) file in the "examples" directory.

All the examples are built from the "examples" directory.

**Comment by christianepeters** [comment]
I took the liberty of writing up a [simplified version of the howto](https://github.com/christianepeters/homomorphic-encryption/blob/main/helib.md) that gets you right to the examples.

**Comment by Hang-shao** [comment]
It's my [node](https://www.cnblogs.com/pam-sh/p/14524581.html)

**Comment by DylanWangWQF** [comment]
Hi, @Hang-shao  @christianepeters  @faberga .
Why do we need to build the NTL as a shared library `libntl.so` rather than `libntl.a` when building the dependencies?

_BUILD_SHARED=ON/OFF (default is OFF): Build as a shared library. Note that building HElib (regardless of BUILD_SHARED) will fail if NTL is not built as a shared library. The default for NTL is static library, to build NTL as a shared library use ./configure SHARED=on in step 1._

In my project, I need to build these as static libraries (e.g., `libhelib.a, libntl.a, libgmp.a`). I'm not clear with these principles.  Thanks in advance!

**Comment by faberga** [comment]
@DylanWangWQF The main reason for linking with libntl.so is a licensing one. NTL is LGPL v2.1+ and HElib is Apache 2, hence the default linking for HElib is with libntl.so.

You are free to link statically, but then you should adhere to the LGPL v2.1+ rules for the distribution and use of your code.

**Comment by ByShui** [comment]
hi，i made a note for describe the install and run examples clearly, but in chinese, if you need：[安装HElib并运行示例程序](https://baishui.blog.csdn.net/article/details/122737035)

**Comment by faberga** [comment]
@ByShui Thank you.
We don't have a version of the documentation in Chinese, but I will keep the link should anyone else ask.

**Comment by faberga** [comment]
Closing as resolved.
