### ISSUE TITLE
Use of AES implementation on HElib

### ISSUE THREAD

**Issue by SlavnicN** [homenc/HElib#54]
I'm trying to use the AES implementation over HElib and I would like to be able to do operation like addition and multiplication on ciphertext after the encryption of an AES(m) over homomorphic encryption.
On simple HE encryption the operations are made over the object Ctxt but when we use the implementation of AES all the cipher text are vector of Ctxt and I can't figure it out how I can manupilate those vector.
Based on Test_AES.cpp I tried to encrypte a vector of 1 like this:

``` c++
Vec<uint8_t> ptxt(INIT_SIZE,nBlocks*16); //Vector of 1
vector<Ctxt> doublyEncrypted;
hAES.homAESenc(doublyEncrypted,encryptedAESkey,ptxt); // Encryption of the vector store
                                                      //in doublyEncrypted
```

So normaly we have `doublyEncrypted = Enc_HE(Enc_AES(myvector))`
Now the decryption

``` c++
hAES.homeAESdec(doublyEncrypted,encryptedAESkey);
```

and now `doublyEncrypted = Enc_HE(myvector)`. At this point I should be able to do some operation on my encrypted vector. As doublyEncrypted is a vector of Ctxt I tried something like:

``` c++
for(long i=0;i<(long)doublyEncrypted.size();i++){
    doublyEncrypted[i].addCtxt(doublyEncrypted[i]);
}
```

But when I decrypt it with the secret key and decode it all a got is a vector of 0.
So my question is, is it possible with this implementations of AES over the HElib to do some operation on the ciphertext or is it just for performence purpose. If it's possible, can you give a simple example doing such operation.

Thanks in advance!

**Comment by shaih** [comment]
A vector of zeros is actually the right answer here.

After homomorphic decryption, `doublyEncrypted[i]` is an HElib ciphertext that encrypts some plaintext blocks, relative to plaintext space modulo 2. Adding a binary vector to itself yields zero, so `doublyEncrypted[i].addCtxt(doublyEncrypted[i])` yields an encryption of blocks of zero.

This is perhaps a reasonable use case, even though it really makes more sense to apply a similar procedure to data encrypted with AES in CTR mode rather than ECB mode as in your example. For two reasons, one is that this way you would compute homomorphic AES encryption of the counter rather than decryption of the blocks (which is faster). But more importantly you really should not be using ECB mode for encryption.

In the CTR-mode case you would encode your AES-CTR encrypted vector as a vector of HElib constants using
```
  Vec<ZZX> myEncryptedDataEncoded;
  encode4AES(myEncryptedDataEncoded, myEncryptedData, ea2);
```
Then prepare a `uint8` vector that contains the counter values (i.e., the i'th 16-byte block in the buffer contains the value i). Then use `hAES.homAESenc(helibEncrypted, counterValues, encryptedAESkey)` to get the AES-encrypted counter values under HElib, and finally do
```
for (long i=0; i<(long)helibEncrypted.size(); i++) {
    helibEncrypted[i].addConstant(myEncryptedDataEncoded[i]);
}
```
Now the vector `helibEncrypted` contains your data, encrypted under HElib (rather than under AES). 

Note that you have one byte of your data in each plaintext slot of every ciphertext `helibEncrypted[i]`. So for example you can do `helibEncrypted[0] += helibEncrypted[1]` and get the xor of some data bytes.

**Comment by SlavnicN** [comment]
I followed your instruction and the cipher/decipher with the AES CTR works well. But once again I can't do any operation on helibEncrypted. 
First when I try to add `helibEncrypted[0] += helibEncrypted[1]` I got an error that says : `Assertion '&context==&other.context && &pubKey==&other.pubKey' failed `.
Also when I try to do an operation on the same value, the vector that I get after deciphering it is not the one expected. For instance for a vector of 3, adding just `helibEncrypted[0] += helibEncrypted[0]` give me a vector of 0 and multiplying it give me a vector of 5. Maybe it's still a probleme of modulus. I tried this on different set of parameters, but I got the same result.

Maybe my initial question wasn't so clear, what I want to do is for 2 differents plaintexts (a,b) cipher with AES (AES(a),AES(b)) and then 'recipher' with homomorphic encryption thanks to you implementation(HE(a),HE(b)). With this two ciphertexts I want to be able to do any kind of homomorphic operation (HE(a)+HE(b) = HE(a+b) for instance) and then get the result by decpyhering it with the secret key. (a+b)

**Comment by rohitkhera** [comment]
This does not seem like a validuse case if what you mean to do is compute the result res = (HE_Enc(AES_Enc(a)) + HE_Enc(AES_Enc(b)) and then expect that AES_Dec(HE_Dec(res)) = a+b 
You have the right idea that the homomorphisms work for plaintexts encrypted under the same BGV public key, but they must be plaintexts that are encrypted under the same public key, not ciphertexts produced by a non homomorphic scheme (viz. AES)

**Comment by shaih** [comment]
> For instance for a vector of 3, adding just helibEncrypted[0] += helibEncrypted[0]
> give me a vector of 0 and multiplying it give me a vector of 5.

As I said before, 0 is the right answer after doing helibEncrypted[0] += helibEncrypted[0]. I don't know what you mean by "a vector of 5", this is a mod-2 plaintext space, it will never give you a 5.

Perhaps what you mean is that you get the bit-string 101? This is not a 5, it is the polynomial X^2+1, so maybe that plaintext slot in the ciphertext helibEncrypted[0] had the polynomial X+1 (and when you multiply it by itself mod-2 you get X^2+1).

My suggestion: try to implement the operations that you want <b>on plaintext data</b>, but using the right plaintext representation. (You can use the PlaintextArray class of HElib to do this, it was meant for debugging and it provides some interfaces for encoding/decoding and manipulations.) Once you are satisfied that you understand the operations that are available to you, then try to carry out the same operations on encrypted data, and see if you get the right thing.

**Comment by SlavnicN** [comment]
Rohitkhera, it's not exactly what I meant to do, what I want to do it's a small example of a client/server, where the client sends some data ciphered under AES with a key K. The server, thanks to the key HE_Enc(K) and the data ciphered under homomorphic scheme HE_Enc(AES(m)) (all with the public key), compute the ciphertext HE_Enc(m). The server can do simple operations on HE_Enc(m) and then forward it back to the client. Then the client deciphers it with the private key and gets m'.

When I say a vector of 5, it's literally this: 
```c++
Vec<uint8_t> msg(INIT_SIZE,nBlocks*16);
for(long i = 0;i<nBlocks*16;i++){
    msg.put(i,5);
}
```
When I played with your library without aes, I used both vector<long> and PlaintextArray for ciphering data and do some homomorphic operations. I assumed it would be the same with your aes implementation but I think I am missing something.

**Comment by shaih** [comment]
> [...] I assumed it would be the same with your aes implementation but I think I am missing something.

Yes, you are.

This implementation of homomorphic-AES uses a mod-2 plaintext arithmetic: more specifically the underlying algebra is GF(2^8), represented wrt the AES polynomial G(X)=X^8+X^4+X^3+X+1. So each byte represents a degree-7 binary polynomial (i.e. an element of GF(2^8)) and the arithmetic operations are polynomial operations modulo 2 and G.

You can apply the AES encryption and decryption without caring about the plaintext space (because I already implemented it for you). But if you want to apply any other operations then you must understand the algebra that's available to you. The operations that you would apply would be GF(2^8) operations on the bytes.

**Comment by SlavnicN** [comment]
Ok, I understand it now, thank you. I didn't realize that all your AES implementation was on GF(2^8).

Is there any way to bypass the limit of the field. I was thinking using a other FHEcontext beside the one used by the AES implementation where I could do any operation on any field. Maybe convert the helibEncrypted in a Ctxt that belong to the new FHEContext. I saw that there is some method for conversion like DummyEncryption that doesn't encrypt but just convert in a Ctxt object, and using the fact that each Ctxtpart can be see as a DoubleCRT.

But I guess that each Ctxt are to tied to there own FHEcontext to be easily convert to a other context. Or maybe copy the keys in a other "bigger" context to apply the operation on the same keys but this I think is impossible consider who keys are generated.

**Comment by faberga** [comment]
Closing as issue/question resolved.
